name: Change Working Dir
on: [push]
defaults:  # Workflow Level defaults
  run:
    shell: bash
jobs:
  make-and-change-directory:
    runs-on: ubuntu-latest
    steps:
      - name: 디렉토리 생성 및 파일 생성
        run: |
          mkdir -p /home/runner/test_folder
          echo "Hi" > /home/runner/test_folder/sample.txt
      - name: 워킹 디렉토리 변경
        working-directory: /home/runner
        run: |
          pwd
          cat sample.txt