name: first-exercise-workflow
on: [push,pull_request]

jobs:
  confirm-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: confirm Python Version & PIP Version
        run: |
          python —version
          pip —version